import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Col, Row } from 'react-bootstrap'
import Pomodoro from '../components/pomodoro'
import TaskCard from '../components/taskCard'

type Task = {
  name: string;
  qttPomodoros: number;
  cpdPomodoros: number;
}

const baseURL = "http://localhost:8080"

export default function Tasks() {
  const [tasks, setTasks] = useState<Task[]>([])

  useEffect(() => {
    axios.get(`${baseURL}/task`)
    .then(response => {
      setTasks(response.data);
    })
  }, [])

  return (
    <>
      <Head>
        <title>Pomogame - Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        <Col>
        {tasks.map(t => {
          return (
            <li key={t.name}>
              <TaskCard name={t.name} qtd={t.qttPomodoros} cpt={t.cpdPomodoros}/>
            </li>
          )
        })}
          
        </Col>
        <Col>
        <Pomodoro />
        </Col>
      </Row>

    </>
  )
}
